spring:
  profiles:
    active:
      -dev
      
---

spring:
  profiles:dev
  application:
    name:microservicecloud-config-university-dev
    
---

spring:
  profiles:test #测试环境
  application:
    name:microservicecloud-config-university-test

# 请保存为UTF-8